### ISSUE TITLE
Streak effect missing alpha channel on LWRP&PPV2

### ISSUE THREAD

**Issue by phields** [keijiro/Kino#11] opened 2019-12-09 04:57 UTC

**Comment by keijiro** [comment] 2019-12-09 06:02
Could you elaborate what you are trying to do? Kino only supports HDRP, so I think you can't do anything with it on LWRP.

**Comment by phields** [comment] 2019-12-09 06:17
@keijiro Thanks for the reply, I'm trying to stream the alpha frames with [spout2](https://github.com/keijiro/KlakSpout)
But I lose the alpha channel info when I enable the Streak effect.
![微信截图_20191209141726](https://user-images.githubusercontent.com/31947421/70412018-ab4f4a80-1a8e-11ea-9fe5-d14bca98f281.png)

**Comment by keijiro** [comment] 2019-12-09 07:25
So, you're using an old version of Kino, right?

I think you can recover the original alpha by modifying the line 80 as follows:
```
return half4(cf + c3, SAMPLE_TEXTURE2D(_HighTex, sampler_HighTex, i.tecoord).a));
```

**Comment by phields** [comment] 2019-12-10 20:55
@phields Thank you!
It seems that the post-processing of the current HDRP/URP pipeline will automatically close the alpha channel... Whether you add effects or not.
That's really bad for mixing video with NDI or spout.

**Comment by keijiro** [comment] 2019-12-11 01:14
As far as I know, the most of the post-processing effects don't preserve alpha values -- It's "by design".

**Comment by keijiro** [comment] 2019-12-11 01:35
In addition to that, HDRP doesn't preserve alpha while rendering. You have to use the AOV feature to capture the alpha channel values.

https://docs.unity3d.com/Packages/com.unity.aovrecorder@0.1/manual/index.html

**Comment by keijiro** [comment] 2019-12-11 01:36
I'm closing this issue now as the problem is not actually relevant to this project. Please feel free to reopen it for further questions.

**Closed as completed by keijiro** 2019-12-11 01:36 UTC
Labels: question

**Comment by keijiro** [comment] 2019-12-11 01:42
@phields I can understand your frustration -- I know that it's important to preserve alpha channel when using an external compositing system. Actually, I'm frustrated with this problem sometimes too. I'd like to solve the problem or make a workaround for it, but at the moment, I don't have any good idea.
